dws:
    resource: "@DWSBundle/Resources/config/routing.yml"
    prefix : /{_locale}/ 
    requirements:
        _locale: '%app.locales%'

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix : /{_locale}/ 
    requirements:
        _locale: '%app.locales%'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix : /{_locale}/ 
    requirements:
        _locale: '%app.locales%'
